//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGites
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.lesContrats = new HashSet<contrat>();
        }
    
        public int numClient { get; set; }
        public string nomClient { get; set; }
        public string adresseClient { get; set; }
        public string cpClient { get; set; }
        public string villeClient { get; set; }
    
        public virtual ICollection<contrat> lesContrats { get; set; }
    }
}
