//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGites
{
    using System;
    using System.Collections.Generic;
    
    public partial class gite
    {
        public gite()
        {
            this.lesPlannings = new HashSet<planning>();
            this.lesTarifs = new HashSet<tarif>();
        }
    
        public int numGite { get; set; }
        public string nomGite { get; set; }
        public string adresseGite { get; set; }
        public string cpGite { get; set; }
        public string villeGite { get; set; }
        public Nullable<short> nbEpis { get; set; }
        public string descriptionGite { get; set; }
    
        public virtual ICollection<planning> lesPlannings { get; set; }
        public virtual ICollection<tarif> lesTarifs { get; set; }
    }
}
