//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGites
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gitesEntities : DbContext
    {
        public gitesEntities()
            : base("name=gitesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<client> clients { get; set; }
        public DbSet<contrat> contrats { get; set; }
        public DbSet<gite> gites { get; set; }
        public DbSet<periode> periodes { get; set; }
        public DbSet<planning> plannings { get; set; }
        public DbSet<semaine> semaines { get; set; }
        public DbSet<tarif> tarifs { get; set; }
    }
}
