//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaoGites
{
    using System;
    using System.Collections.Generic;
    
    public partial class periode
    {
        public periode()
        {
            this.lesSemaines = new HashSet<semaine>();
            this.lesTarifs = new HashSet<tarif>();
        }
    
        public int numPeriode { get; set; }
        public Nullable<System.DateTime> dateDebutPeriode { get; set; }
        public Nullable<System.DateTime> dateFinPeriode { get; set; }
    
        public virtual ICollection<semaine> lesSemaines { get; set; }
        public virtual ICollection<tarif> lesTarifs { get; set; }
    }
}
